filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /data/user_database.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: user_database
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/server-assignment/assignments.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: server_assignment
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
